### ISSUE TITLE
Incorrect content for ContainerClient and PageBlobClient

### ISSUE THREAD

**Issue by zhiweiv** [MicrosoftDocs/azure-docs-sdk-node#1003]
https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/containerclient?view=azure-node-latest#ContainerClient_string__Pipeline_

> A URL string pointing to Azure Storage page blob, such as "https://myaccount.blob.core.windows.net/mycontainer/pageblob".

It should be container url?

https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/pageblobclient?view=azure-node-latest#PageBlobClient_string__Pipeline_

> A Client string pointing to Azure Storage blob service, such as "https://myaccount.blob.core.windows.net".

It should be page blob url?

**Comment by ramya-rao-a** [comment]
Thanks for reporting @zhiweiv 

@ljian3377, Can you please take a look?
