### ISSUE TITLE
container.item(<id>).read() does not work

### ISSUE THREAD

**Issue by sijucm** [MicrosoftDocs/azure-docs-sdk-node#1004]
The page shows example with container.item(1).read(). It did not work for me and I found the solution from stackoverflow, after wasting some time because of this documentation, that item(<id>, <partitionKey>) should be used. I tried also the read({partitionKey:<partiionKey>}) as well but that also does not work. That way was found in some other Microsoft documentation. Maybe this is an SDK version difference, but then it should be made clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4bed5dc-c173-b7b9-f52d-a4ead58e15c0
* Version Independent ID: 27ed24eb-b98a-7c2d-dd29-23893ab38b74
* Content: [Azure Cosmos DB client library for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/cosmos-readme?view=azure-node-latest)
* Content Source: [docs-ref-services/latest/cosmos-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/cosmos-readme.md)
* Service: ****
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @sijucm 

@southpolesteve, @zfoster Can we have the content here fixed? The file to update is https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/cosmos-readme.md

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of https://github.com/Azure/azure-sdk-for-js/issues/13518
