### ISSUE TITLE
Sample javascript code missing an element

### ISSUE THREAD

**Issue by Dack3n** [MicrosoftDocs/azure-docs-sdk-node#1010]
Within the "event" body, the "eventTime" must be provided. I was able to fire the event and see it in my azure portal after adding in a correctly formatted DateTime.

Cheers,
Jesse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb1e0b0-bee3-eeb8-fd9c-04e3892fe0d4
* Version Independent ID: cb6a421e-8ed0-8415-e73e-a1af9ecfe54b
* Content: [Azure Event Grid libraries for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/eventgrid?view=azure-node-latest)
* Content Source: [docs-ref-services/latest/eventgrid.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/eventgrid.md)
* Service: **event-grid**
* Product: ****
* Technology: ****
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Dack3n

Would you be interested in creating a PR to fix this? The file to update would be https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/eventgrid.md

**Comment by ramya-rao-a** [comment]
On the other hand, we will be updating this page to favor the newer `@azure/eventgrid` package and removing the code sample for azure-eventgrid package which is being done as part of https://github.com/MicrosoftDocs/azure-docs-sdk-node/issues/678 in https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/1059

So, will close this issue
