### ISSUE TITLE
Normalize DocDB/Cosmos DB samples

### ISSUE THREAD

**Issue by fiveisprime** [MicrosoftDocs/azure-docs-sdk-node#16]
The samples page (https://docs.microsoft.com/en-us/nodejs/azure/node-samples-services-database?view=azure-node-2.0.0) includes samples for both DocumentDB and Cosmos DB. The DocumentDB examples need to be updated to use Cosmos DB and the grouping should also be adjusted.

**Comment by KarlErickson** [comment]
Updated URL: https://docs.microsoft.com/en-us/javascript/azure/node-samples-services-database?view=azure-node-latest
