### ISSUE TITLE
Need client samples for Key Vault

### ISSUE THREAD

**Issue by fiveisprime** [MicrosoftDocs/azure-docs-sdk-node#203]
The key vault docs only include the management plane pieces. This should be expanded to show the client functionality or, at least, point to the client SDK for these kinds of operations:

* Manage keys: create, import, update, delete, backup, restore, list and get
* Key operations: sign, verify, encrypt, decrypt, wrap, unwrap
* Secret operations: set, get, update and list
* Certificate operations: create, get, update, import, list, and manage contacts and issuers

**Comment by KarlErickson** [comment]
Spoke with @fiveisprime and determined that what is being requested is snippet coverage of these scenarios in the reference documentation. Currently, only basic snippets are present.

**Comment by ramya-rao-a** [comment]
The latest set of API reference docs for the below packages have inline code snippets
- [@azure/keyvault-keys](https://docs.microsoft.com/en-us/javascript/api/%40azure/keyvault-keys/keyclient?view=azure-node-latest)
- [@azure/keyvault-certificates](https://docs.microsoft.com/en-us/javascript/api/@azure/keyvault-certificates/certificateclient?view=azure-node-latest)
- [@azure/keyvault-secrets](https://docs.microsoft.com/en-us/javascript/api/@azure/keyvault-secrets/secretclient?view=azure-node-latest)
