### ISSUE TITLE
Examples!

### ISSUE THREAD

**Issue by RickBullotta** [MicrosoftDocs/azure-docs-sdk-node#317]
Any API documentation is 10-100X more valuable if concrete examples are provided for common processes such as an end-to-end example of a device provisioning itself, setting tags, etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a9df1f-cafd-844b-301f-554555d8f9ae
* Version Independent ID: 2a886da6-a7d4-38b6-37df-a2d74153a58e
* Content: [azure-iot-provisioning-device package](https://docs.microsoft.com/en-us/javascript/api/azure-iot-provisioning-device/?view=azure-node-latest)
* Content Source: [ts-packages/docs-ref-autogen/azure-iot-provisioning-device/index.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/live/ts-packages/docs-ref-autogen/azure-iot-provisioning-device/index.yml)
* Service: **unspecified**

**Comment by ramya-rao-a** [comment]
@anthonyvercolano, Can someone from your team take a look at this? Not sure if this is still applicable. If it is, I believe moving this issue to https://github.com/Azure/azure-iot-sdk-node would be the right move

**Comment by anthonyvercolano** [comment]
Copied the bug.  I don't have the privs to close.

**Comment by ramya-rao-a** [comment]
Closing as we will be tracking this in https://github.com/Azure/azure-iot-sdk-node/issues/932
