### ISSUE TITLE
Getting error on the 'get' method for this class

### ISSUE THREAD

**Issue by RickBullotta** [MicrosoftDocs/azure-docs-sdk-node#320]
Getting an error when trying to invoke the 'get' method on an object returned from the Client getTwin() method.  The get method does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ef8936-1dae-b904-1720-cf6bf4d4ab78
* Version Independent ID: b426ed8b-4bb1-2c3c-20cb-12ea28e961dd
* Content: [Twin class](https://docs.microsoft.com/en-us/javascript/api/azure-iot-device/twin?view=azure-node-latest)
* Content Source: [ts-packages/docs-ref-autogen/azure-iot-device/Twin.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/live/ts-packages/docs-ref-autogen/azure-iot-device/Twin.yml)
* Service: **unspecified**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @RickBullotta 

@anthonyvercolano, Can someone from your team take a look at this?

**Comment by anthonyvercolano** [comment]
Carried over to our repo.  Someone with priv needs to close this one.

**Comment by ramya-rao-a** [comment]
Close this issue as we will be tracking it in https://github.com/Azure/azure-iot-sdk-node/issues/933
