### ISSUE TITLE
Device Id

### ISSUE THREAD

**Issue by abramjstamper** [MicrosoftDocs/azure-docs-sdk-node#347]
Should the device description have the additional fields listed here that are available, but undocumented in MS Docs like status and authentication? (see this PR https://github.com/Azure/azure-iot-sdk-node/pull/309)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2991e7d2-7067-9aed-88cc-99d9c5dde2b4
* Version Independent ID: a9416965-3ef1-954f-7d6d-5d43ac39ab80
* Content: [DeviceDescription interface](https://docs.microsoft.com/en-us/javascript/api/azure-iothub/registry.devicedescription?view=azure-node-latest)
* Content Source: [ts-packages/docs-ref-autogen/azure-iothub/Registry.DeviceDescription.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/live/ts-packages/docs-ref-autogen/azure-iothub/Registry.DeviceDescription.yml)

**Comment by ramya-rao-a** [comment]
Thanks for reporting @abramjstamper 

@anthonyvercolano, Can someone from your team take a look at this?

**Comment by anthonyvercolano** [comment]
This has been carried over by the issue in [azure/azure-iot-sdk-node #934](https://github.com/Azure/azure-iot-sdk-node/issues/934)

**Comment by ramya-rao-a** [comment]
Closing as we will be tracking this in https://github.com/Azure/azure-iot-sdk-node/issues/934
