### ISSUE TITLE
toArray doesn't return Promise at all!

### ISSUE THREAD

**Issue by longsoft-dev** [MicrosoftDocs/azure-docs-sdk-node#353]
This document is a little deceptive? The API doesn't support Promise as far as I can see from the source code. You still need to pass in a callback function to e.g. toArray() and can't use:
var docs = await iter.toArray()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613e4a33-bef2-b33c-6931-172e1541b54f
* Version Independent ID: 237136db-3840-4624-8ecd-ee5781b0efca
* Content: [QueryIterator class](https://docs.microsoft.com/en-us/javascript/api/%40azure/cosmos/queryiterator?view=azure-node-latest#toarray)
* Content Source: [ts-packages/docs-ref-autogen/@azure/cosmos/QueryIterator.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/live/ts-packages/docs-ref-autogen/@azure/cosmos/QueryIterator.yml)

**Comment by ramya-rao-a** [comment]
I am guessing this is an issue with the older version of the `@azure/cosmos` package

The `QueryIterator` class in the latest version of the `@azure/cosmos` package does not have the `toArray` method anymore.
The methods `fetchAll` and `fetchNext` on this class in the latest version of the package does return a promise.

cc @zfoster
