### ISSUE TITLE
Aborter.None has been renamed to Aborter.none in 10.1.0-preview of @azure/storage-blob

### ISSUE THREAD

**Issue by XiaoningLiu** [MicrosoftDocs/azure-docs-sdk-node#402]
Aborter.None has been renamed to Aborter.none in 10.1.0-preview of @azure/storage-blob, seems the document above is not fully updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fea566e-6e5a-363a-8dd6-74e2b21fb348
* Version Independent ID: 14710998-1130-3128-938a-25fc21b413fd
* Content: [Aborter class](https://docs.microsoft.com/en-us/javascript/api/%40azure/storage-blob/aborter?view=azure-node-preview#none)
* Content Source: [preview-packages/docs-ref-autogen/@azure/storage-blob/Aborter.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/live/preview-packages/docs-ref-autogen/@azure/storage-blob/Aborter.yml)

**Comment by KarlErickson** [comment]
Doc now shows Aborter.none.
