### ISSUE TITLE
Missing API reference for Node.js

### ISSUE THREAD

**Issue by codefoster** [MicrosoftDocs/azure-docs-sdk-node#405]
Azure Storage is a commodity service and Node.js is one of the most popular runtimes in the world and we don't have detailed documentation (an API reference) for it. I search Azure Storage Documentation for a certain method (listBlobsSegmented) and I get 0 results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93284063-6cd1-1860-2f90-71db47c0a1dd
* Version Independent ID: 9ea83e77-7277-cd01-d340-734d6146b51f
* Content: [Azure Storage modules for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/storage?view=azure-node-latest)
* Content Source: [docs-ref-services/storage.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/storage.md)
* Service: **storage**
* Product: **azure**
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by mhopkins-msft** [comment]
@codefoster is this what you need?

https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/?view=azure-node-latest

**Comment by codefoster** [comment]
@mhopkins-msft, the issue is not so much the unavailability of the documentation you pointed to, but the inability to discover it doing a [search for listBlobsSegmented from Azure Storage Documentation](https://docs.microsoft.com/en-us/search/?search=listBlobsSegmented&scope=Azure&category=Documentation&skip=0), which brings up 3 results - two of which are .NET and one of which is rather unrelated.

**Comment by tamram** [comment]
#reassign: @tamram

**Comment by tamram** [comment]
@codefoster - Thanks for your feedback!

I know you opened this some time ago. I think the search functionality has improved in the meantime. The latest JavaScript package for blobs is now v12.x, and it no longer supports the listBlobsSegmented method. Instead the [ContainerClient class](https://docs.microsoft.com/javascript/api/@azure/storage-blob/containerclient?view=azure-node-latest) includes the following listing methods:

- listBlobsByHierarchy(string, ContainerListBlobsOptions)
- listBlobsFlat(ContainerListBlobsOptions)

I am able to locate these in the reference by searching the Azure Storage Documentation. Both searches return the ContainerClient class.

Please let us know if you encounter any further issues.

#please-close

**Comment by tamram** [comment]
@noelbundick - Could you close this one?

**Comment by codefoster** [comment]
I'm fine with closing this. Glad to see the improvements. Thanks.
