### ISSUE TITLE
[Node][Reference] Link to reference of Azure for Node.js wrong

### ISSUE THREAD

**Issue by zhiliangxu** [MicrosoftDocs/azure-docs-sdk-node#424]
Look at the page here: https://docs.microsoft.com/en-us/javascript/azure/?view=azure-node-latest
![image](https://user-images.githubusercontent.com/2852646/48041494-57ea3900-e1b8-11e8-9f93-a01171dbd572.png)

Seems the link of Reference is incorrect.

// Copied from https://dev.azure.com/ceapex/Engineering/_workitems/edit/48455

**Comment by KarlErickson** [comment]
Fixed
