### ISSUE TITLE
wheres the source

### ISSUE THREAD

**Issue by andersponders** [MicrosoftDocs/azure-docs-sdk-node#429]
is the source for this SDK up somewhere or is all we get the zip with the bundle in it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d76dde8-c24c-db44-3487-a058759273de
* Version Independent ID: d6fcf3de-633b-660b-c55c-9a00dc979e22
* Content: [Cognitive Services Speech SDK for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/speech-service?view=azure-node-latest)
* Content Source: [docs-ref-services/speech-service.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/speech-service.md)
* Service: **cognitive-services**
* Product: **azure**
* GitHub Login: @mahilleb-msft
* Microsoft Alias: **mahilleb**

**Comment by mahilleb-msft** [comment]
Hi @andersponders,

currently the .ZIP is all there is, but we're working on putting out an NPM package and source (hopefully this year, but it could slip into next).

Best, Mark

**Comment by mahilleb-msft** [comment]
Check out https://github.com/Microsoft/cognitive-services-speech-sdk-js and https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk.

#please-close
