### ISSUE TITLE
How to create a table?

### ISSUE THREAD

**Issue by zea7ot** [MicrosoftDocs/azure-docs-sdk-node#430]
How to create a table?
How to create a method like createTableIfNotExisting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16cc0734-3d62-4af4-a42e-1e9039cb3379
* Version Independent ID: a087b2a8-3c5b-575a-c5f7-0e030fd2900b
* Content: [Azure SQL modules for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/sql?view=azure-node-latest)
* Content Source: [docs-ref-services/sql.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/sql.md)
* Service: **sql-database**
* Product: **azure**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
IF EXISTS (SELECT * FROM sys.objects 
WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[mySampleTable]') AND TYPE IN (N'U'))
DROP TABLE [dbo].[mySampleTable]

**Comment by CarlRabeler** [comment]
#please-close

**Comment by CarlRabeler** [comment]
#please-close
