### ISSUE TITLE
azure-eventgrid EventGridClient() second argument

### ISSUE THREAD

**Issue by justono1** [MicrosoftDocs/azure-docs-sdk-node#438]
The Documentation states pass a string of 'your-subsciber-id' when the latest package from npm takes an optional argument of AzureServiceClientOptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6ba0031-7cb0-cd93-cb24-989b34fa2e3b
* Version Independent ID: cb6a421e-8ed0-8415-e73e-a1af9ecfe54b
* Content: [Azure Event Grid libraries for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/eventgrid?view=azure-node-latest)
* Content Source: [docs-ref-services/eventgrid.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/eventgrid.md)
* Service: **event-grid**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by hanvyj** [comment]
Is there no response to this? It's been open for most of a year - kind of makes the documentation useless. This is the only example I can find and it simply doesn't work.

**Comment by svbeon** [comment]
These docs references the package `azure-eventgrid` but if you look at "Client" in the side menu it shows the API for `@azure/eventgrid` - Which one is correct?

**Comment by ramya-rao-a** [comment]
With #1059 we are moving away from having code sample for the individual packages in the landing page for the service in the ref docs. That pre-empts the problem presented here

Also, we will soon release v3 of `@azure/eventgrid` that will come with extensive samples. You can get a look at those in https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/eventgrid/eventgrid/samples

Thanks for reporting!
