### ISSUE TITLE
in the options blobAccessConditions should be accessConditions

### ISSUE THREAD

**Issue by johnataylor** [MicrosoftDocs/azure-docs-sdk-node#465]
Check the implementation of the block blob upload for usage, this is current a direct line to a line of code, however just take a look at the implementation of the BlockBlobURL.upload function:

https://github.com/Azure/azure-storage-js/blob/a1b7084089bf85dd166aa8e89745964ea263d13a/blob/lib/BlockBlobURL.ts#L180

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f229a6-ac9f-b47a-f507-dc819232740d
* Version Independent ID: 46a286fc-9970-dadb-0a85-4ad48163bd34
* Content: [IUploadToBlockBlobOptions interface](https://docs.microsoft.com/en-us/javascript/api/%40azure/storage-blob/iuploadtoblockbloboptions?view=azure-node-preview#blobaccessconditions)
* Content Source: [preview-packages/docs-ref-autogen/@azure/storage-blob/IUploadToBlockBlobOptions.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/live/preview-packages/docs-ref-autogen/@azure/storage-blob/IUploadToBlockBlobOptions.yml)

**Comment by ramya-rao-a** [comment]
@ljian3377 This is regarding the v10 of `@azure/storage-blob` package. Can you provide any clarification here?

**Comment by ljian3377** [comment]
We don't plan to fix doc issues for the V10.

We have a more serious issue with V10 as it depends on the axios which has security issues but we don't plan to it too. Maybe we need some kind of deprecation of V10.

**Comment by ramya-rao-a** [comment]
Thanks @ljian3377 

Closing this issue as the guidance is to use the latest v12 of the storage packages rather than v10 for which this issue is logged
