### ISSUE TITLE
Landing page: Remove "Azure Node SDK" menu

### ISSUE THREAD

**Issue by auchenberg** [MicrosoftDocs/azure-docs-sdk-node#473]
We should remove the Remove "Azure Node SDK" menu as there's nothing to select between.
![screen shot 2019-02-22 at 2 26 36 pm](https://user-images.githubusercontent.com/173559/53274947-08b80d80-36ae-11e9-9256-59772264904b.png)

Python don't have one, https://docs.microsoft.com/en-us/python/azure/?view=azure-python

**Comment by KarlErickson** [comment]
There's no preview content right now, so the Preview option is spurious. Also, it shouldn't say Azure Node SDK since it has conceptual in it as well as ref.

**Comment by KarlErickson** [comment]
Turns out there is preview content in the reference area, so we need to keep this.

**Comment by auchenberg** [comment]
@KarlErickson What content is in preview?

**Comment by KarlErickson** [comment]
For example, https://docs.microsoft.com/en-us/javascript/api/azure-cognitiveservices-customimagesearch/?view=azure-node-preview.

**Comment by auchenberg** [comment]
@KarlErickson Do you know which team that owns this content, and why we have "reference" documentation for SDKs as part of these docs?
