### ISSUE TITLE
Landing page: Clean up "Overview" node

### ISSUE THREAD

**Issue by auchenberg** [MicrosoftDocs/azure-docs-sdk-node#476]
We should clean up the "Overview" node by either removing it,  or adding more content to. "Azure Modules" node doesn't make much sense on the context of not being SDK/reference docs.

![screen shot 2019-02-22 at 4 38 05 pm](https://user-images.githubusercontent.com/173559/53278803-69e8dc80-36c0-11e9-9e4d-4661670c6ad6.png)

**Comment by KarlErickson** [comment]
Remove for now?

**Comment by ramya-rao-a** [comment]
@diberry, Can you take a call on this?

**Comment by diberry** [comment]
#please-close
