### ISSUE TITLE
Landing page: Update "Quickstarts" Node with TOC from index

### ISSUE THREAD

**Issue by auchenberg** [MicrosoftDocs/azure-docs-sdk-node#477]
We should update the "Quickstarts" Node with TOC from index/homepage. Right now they are out of sync.

![screen shot 2019-02-22 at 4 48 11 pm](https://user-images.githubusercontent.com/173559/53278974-c26ca980-36c1-11e9-8b2a-2e99b2415544.png)

**Comment by KarlErickson** [comment]
TOC should match the cards.
