### ISSUE TITLE
Landing page: Decide what to do with "How To Guides" node

### ISSUE THREAD

**Issue by auchenberg** [MicrosoftDocs/azure-docs-sdk-node#478]
Decide what to do with "How To Guides" node. Keep? Remove? Screen content?

![screen shot 2019-02-22 at 4 49 29 pm](https://user-images.githubusercontent.com/173559/53279006-ec25d080-36c1-11e9-8bfc-f4c474a11369.png)

**Comment by ramya-rao-a** [comment]
@diberry, Can you take a call on this?

**Comment by diberry** [comment]
This is already in progress @ramya-rao-a Can we please close? #please-close
