### ISSUE TITLE
Landing page: Decide what to do with "Samples" node. Keep? Remove? Screen content?

### ISSUE THREAD

**Issue by auchenberg** [MicrosoftDocs/azure-docs-sdk-node#479]
![screen shot 2019-02-22 at 4 49 34 pm](https://user-images.githubusercontent.com/173559/53279007-f34cde80-36c1-11e9-89d8-8fdd9cba2951.png)

**Comment by ramya-rao-a** [comment]
@diberry Can you take a call on this?

**Comment by diberry** [comment]
@ramya-rao-a  A teams call? Or do you mean make a decision?

**Comment by ramya-rao-a** [comment]
A decision :)

**Comment by diberry** [comment]
Already dealt with this, sorry for not letting you know. Single link to samples browser now with ts/js/node checked. #please-close
