### ISSUE TITLE
Landing page: Reorganize sections (under debate)

### ISSUE THREAD

**Issue by auchenberg** [MicrosoftDocs/azure-docs-sdk-node#485]
Move sections around on landing page to this order:
- Free
- Hosting
- DevOps
- Debugging
- Tools
- Storage
- Auth
- Monitoring
- Messaging
- IOT
- SDK

**Comment by kraigb** [comment]
@auchenberg Has there been any more thought about this? I know that there's a question about the SDK being last, with clicktale data suggesting it'd be much better to have it earlier, probably right after hosting.
