### ISSUE TITLE
Add contextual TOC parameters to links from dev-center cards on the landing page

### ISSUE THREAD

**Issue by KarlErickson** [MicrosoftDocs/azure-docs-sdk-node#502]

**Comment by ramya-rao-a** [comment]
Hey @KarlErickson,
Can you provide any more details or context on this issue?

@diberry,
Assigning to you as this is most likely related to the dev center cards on https://docs.microsoft.com/en-us/javascript/azure/?view=azure-node-latest

**Comment by KarlErickson** [comment]
@ramya-rao-a @diberry not sure if this is still relevant. Any links in the hub-page cards that are in the dev-center TOC, but where the link itself is for a topic in another TOC (such as a service topic) should have contextual parameters to preserve the presence of the dev-center TOC.

**Comment by diberry** [comment]
@KarlErickson I've seen UI studies that say this is confusing to customers. Is this a repo-wide requirement?

**Comment by KarlErickson** [comment]
@diberry no, not a requirement. Feel free to disregard.

**Comment by ramya-rao-a** [comment]
Closing for now as there is no agreed upon next steps here.
