### ISSUE TITLE
Content is ancient

### ISSUE THREAD

**Issue by benc-uk** [MicrosoftDocs/azure-docs-sdk-node#576]
This is linked to from the main "Getting started with Azure and JavaScript" page https://docs.microsoft.com/en-us/javascript/azure/?view=azure-node-latest

Yet the content is extremely out of date an uses the deprecated SDK https://github.com/Azure/azure-sdk-for-js/blob/master/documentation/Migration.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8540c2-c757-380e-c6cf-27bbb986fe9a
* Version Independent ID: 1221b44d-8c64-08fc-b57e-9bf4b43e0ece
* Content: [Get started with the Azure modules for Node.js](https://docs.microsoft.com/en-us/javascript/azure/node-sdk-azure-get-started?view=azure-node-latest)
* Content Source: [docs-ref-conceptual/node-sdk-azure-get-started.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-conceptual/node-sdk-azure-get-started.md)
* Service: **azure-nodejs**
* Product: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @benc-uk and our apologies for not responding sooner

@diberry While a lot of content here has changed in https://docs.microsoft.com/en-us/javascript/azure/?view=azure-node-latest, can you do a review of https://docs.microsoft.com/en-us/javascript/azure/?view=azure-node-latest to make sure we are not pointing to any older packages?

**Comment by diberry** [comment]
Clean is in progress. @benc-uk Is there a specific page you were concerned about or just a general clean up? The content is currently going through a refresh which is not complete.

**Comment by benc-uk** [comment]
I created this issue a while ago, at the time the SDKs were undergoing another rewrite. I recall finding links to outdated repos and docs. I would have assumed things are better now

**Comment by ramya-rao-a** [comment]
Thanks @benc-uk!

Will close this one for now, please do feel free to log a new issue if you find any issue with the docs.
We will be keeping a closer eye on the issues than before
