### ISSUE TITLE
Links to the samples are broken

### ISSUE THREAD

**Issue by jvineveld** [MicrosoftDocs/azure-docs-sdk-node#626]
The 4 'Getting started with' links are not working, they result in a 404

https://docs.microsoft.com/nl-nl/javascript/api/overview/azure/storage?view=azure-node-latest

**Comment by ramya-rao-a** [comment]
Thanks for reporting @jvineveld and our apologies for not responding sooner

The storage overview page has seen quite some updates over the last year. I don't see any getting started links in https://docs.microsoft.com/en-us/javascript/api/overview/azure/storage-overview?view=azure-node-latest at the moment.

Closing this issue for now
