### ISSUE TITLE
Please update the Samples link.

### ISSUE THREAD

**Issue by chandrakantaS** [MicrosoftDocs/azure-docs-sdk-node#650]
This is out dated and shows 404 page not found:

https://docs.microsoft.com/en-us/javascript/api/overview/azure/storage?view=azure-node-latest#samples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93284063-6cd1-1860-2f90-71db47c0a1dd
* Version Independent ID: 9ea83e77-7277-cd01-d340-734d6146b51f
* Content: [Azure Storage modules for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/storage?view=azure-node-latest#samples)
* Content Source: [docs-ref-services/storage.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/storage.md)
* Service: **storage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by tamram** [comment]
#reassign: @tamram

**Comment by tamram** [comment]
@chandrakantaS - Thanks for your feedback. I'm no longer seeing the 404. Is there still an issue here?

**Comment by tamram** [comment]
@noelbundick - Could you please close? Thanks!

**Comment by noelbundick** [comment]
@tamram I'm afraid you might have me confused for the content owner for these issues. I can't close this item, and I'm not on the team that owns this

**Comment by tamram** [comment]
@noelbundick - Sorry about that!

**Comment by tamram** [comment]
#please-close

**Comment by scbedd** [comment]
@tamram Yeah no problem let me close this.

If you need assistance w/ any of the following repositories:

Azure/azure-docs-sdk-dotnet
Azure/azure-docs-sdk-java
MicrosoftDocs/azure-docs-sdk-node
MicrosoftDocs-azure-docs-sdk-python

I can help you out. Feel free to reach out directly to me on teams as well.
