### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by mjmhall** [MicrosoftDocs/azure-docs-sdk-node#656]
The following links don't work:

Securing a web API with Azure AD - https://azure.microsoft.com/resources/samples/active-directory-node-webapi/

Integrating Azure AD into a NodeJS web application -  https://azure.microsoft.com/resources/samples/active-directory-node-webapp-openidconnect/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed4eae4e-e7aa-913c-b37e-4c030e7e21b0
* Version Independent ID: 49051203-4c9a-afe3-e6a6-d34ca1d9426b
* Content: [Azure Active Directory Modules for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/activedirectory?view=azure-node-latest#feedback)
* Content Source: [docs-ref-services/activedirectory.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/activedirectory.md)
* Product: **azure**
* Technology: **azure**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @mjmhall 

Looks like @CelesteDG has pushed a change to remove the links now, but retained the listing of samples.

Closing in favor of https://github.com/MicrosoftDocs/azure-docs-sdk-node/issues/759 which is tracking the same problem
