### ISSUE TITLE
Use async / await with try catch on demo docs.

### ISSUE THREAD

**Issue by allanchua101** [MicrosoftDocs/azure-docs-sdk-node#673]
[Enter feedback here]
The document looks quite old and it requires more cognitive effort to read for developers used to async/await in NodeJS. 

To solve the issue, implementing the sample on async/await with try catch will reduce callback hell and cognitive workload required to understand sample better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d76dde8-c24c-db44-3487-a058759273de
* Version Independent ID: d6fcf3de-633b-660b-c55c-9a00dc979e22
* Content: [Cognitive Services Speech SDK for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/speech-service?view=azure-node-latest#feedback)
* Content Source: [docs-ref-services/speech-service.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/speech-service.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @mahilleb-msft
* Microsoft Alias: **mahilleb**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @allanchua101 and our apologies for the late response

I have created an issue for this in the repo for the `microsoft-cognitiveservices-speech-sdk` package. Please subscribe to https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/316 for updates.

You are also welcome to send a PR to fix this up as well. The file to update would be https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/speech-service.md
