### ISSUE TITLE
npm package confusion azure- or @azure/?

### ISSUE THREAD

**Issue by swantzter** [MicrosoftDocs/azure-docs-sdk-node#678]
These docs references the package `azure-eventgrid` but if you look at "Client" in the side menu it shows the API for `@azure/eventgrid` - Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6ba0031-7cb0-cd93-cb24-989b34fa2e3b
* Version Independent ID: cb6a421e-8ed0-8415-e73e-a1af9ecfe54b
* Content: [Azure Event Grid libraries for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/eventgrid?view=azure-node-latest)
* Content Source: [docs-ref-services/eventgrid.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/eventgrid.md)
* Service: **event-grid**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @swantzter and apologies for the delay in response

@ellismg Can you update the page athttps://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/eventgrid.md to point to `@azure/eventgrid` instead?  You can use https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/service-bus.md as a reference.

Please add a table for both v2 and v3, mention that the latter is in preview

**Comment by ramya-rao-a** [comment]
@ellismg I have gone ahead and made the changes in #1059. Please review

**Comment by ramya-rao-a** [comment]
This is now fixed. See https://docs.microsoft.com/en-us/javascript/api/overview/azure/eventgrid

Thanks!

**Comment by swantzter** [comment]
Thank you!
