### ISSUE TITLE
Usage of this page via Azure Portal

### ISSUE THREAD

**Issue by noelbundick** [MicrosoftDocs/azure-docs-sdk-node#692]
When you visit the Overview page of a Storage Account in the Azure Portal, there is a Tools and SDKs -&gt; Node.js link that points to this page, hosting it in an iframe

There are a number of links on this page to npm for the storage client libraries

npm sets the "x-frame-options: DENY" header, which prevents it from being displayed in said iframe

The end result is that when trying to learn how to use Azure Storage with JS from the Azure Portal, you get a broken link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93284063-6cd1-1860-2f90-71db47c0a1dd
* Version Independent ID: 9ea83e77-7277-cd01-d340-734d6146b51f
* Content: [Azure Storage modules for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/storage?view=azure-node-latest)
* Content Source: [docs-ref-services/storage.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/storage.md)
* Service: **storage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by craigshoemaker** [comment]
Unfortunately, this page no longer exists.

#please-close

**Comment by noelbundick** [comment]
@craigshoemaker This is still broken in the Azure Portal in prod as of 2020-06-30. Repro steps:

Open a Storage Account, scroll to Tools and SDKs
![image](https://user-images.githubusercontent.com/1970162/86182765-6996f780-bae5-11ea-8536-f732d04ed41b.png)

Visit Node.js
![image](https://user-images.githubusercontent.com/1970162/86182816-829fa880-bae5-11ea-82b2-b2b38244f108.png)

Click @azure/storage-blob, page load fails
![image](https://user-images.githubusercontent.com/1970162/86182845-8e8b6a80-bae5-11ea-9906-5999a6e30d0d.png)

Console shows X-Frame-Options error
![image](https://user-images.githubusercontent.com/1970162/86182876-9cd98680-bae5-11ea-8af1-ab919e5ea49e.png)

+ @jongio for SDK team awareness

**Comment by jongio** [comment]
@maggiepint @kaerm - Can we help get this fixed?

**Comment by kaerm** [comment]
@rishabpoh could you help with this?

**Comment by tamram** [comment]
#reassign: @rishabpoh

**Comment by noelbundick** [comment]
Noticed activity on this & rechecked. - looks like this issue has been resolved. SDK links now open in a new tab versus an iframe blade.
