### ISSUE TITLE
More realistic example using FileShare to download images

### ISSUE THREAD

**Issue by luistrigueiros** [MicrosoftDocs/azure-docs-sdk-node#720]
Hi I am looking for a more realistic example of Node.JS SDK for File Share client API that showcases downloading. something like a image. or pdf file and not just a simple text file.
My problem is with the download example it does not show how to treat binary content.
In particular the example:

[basic auth](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-file-share/samples/typescript/src/basic.ts
)

And the function:

> async function streamToString(readableStream: NodeJS.ReadableStream) 

I would like to see an example on stream to byte array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 764e52a8-c412-1c77-bb9f-9db165c8b4f1
* Version Independent ID: bea79442-2590-5fb2-34b5-77fa9d065e4e
* Content: [Azure Storage modules for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/storage-overview?view=azure-node-latest)
* Content Source: [docs-ref-services/storage-overview.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/storage-overview.md)
* Service: **storage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by luistrigueiros** [comment]
Hi I found what I wanted with the download to buffer method in the FileClient.

**Comment by maggiepint** [comment]
Excellent
