### ISSUE TITLE
Do we have ConfigureRefresh kind option available like .NET SDK

### ISSUE THREAD

**Issue by githubavi** [MicrosoftDocs/azure-docs-sdk-node#724]
Do we have ConfigureRefresh kind option available like .NET SDK? basically like to refresh Key values in specific interval or do it in event driven way

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f508c9f-6a6a-f8b2-5458-8ff07766b5ae
* Version Independent ID: bf71f0f5-fec7-6fc3-e1b2-80c80a6bdc0e
* Content: [Azure App Configuration client library for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/app-configuration-readme?view=azure-node-latest#feedback)
* Content Source: [docs-ref-services/app-configuration-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/app-configuration-readme.md)
* Service: **appconfiguration**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by ramya-rao-a** [comment]
@richardpark-msft Do you have any insights here?

@githubavi , Thanks for reporting and apologies for the delay in response. For further questions, please log an issue at https://github.com/Azure/azure-sdk-for-js

**Comment by richardpark-msft** [comment]
Hi @githubavi, we don't have that feature in the JavaScript SDK for App Configuration, unfortunately.

**Comment by richardpark-msft** [comment]
(Closing this issue for now. If anything changes here I will update it)
