### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by DrachovDmytro** [MicrosoftDocs/azure-docs-sdk-node#746]
Link "App Service Mobile completed quickstart for JavaScript backend" is 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e9dea72-c62e-2d8e-88e3-368047ef25cf
* Version Independent ID: d2c061df-ac84-f063-6dd5-17a9f302f7a1
* Content: [Azure Notification Hubs modules for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/notification-hubs?view=azure-node-latest)
* Content Source: [docs-ref-services/notification-hubs.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/notification-hubs.md)
* Service: **notification hubs**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **ROutlaw**

**Comment by ramya-rao-a** [comment]
@mpodwysocki Can you please provide the right links to use here?
The page in question is [Azure Notification Hubs modules for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/notification-hubs?view=azure-node-latest) and the source md file to fix is https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/notification-hubs.md

**Comment by mpodwysocki** [comment]
@ramya-rao-a The proper link for the [App Service Mobile completed quickstart for Node.js backend](https://github.com/Azure-Samples/app-service-mobile-nodejs-backend-quickstart) is on GitHub in an archived repository.

**Comment by ramya-rao-a** [comment]
Thanks @mpodwysocki 
There are 2 links that are giving 404

![image](https://user-images.githubusercontent.com/16890566/107098592-67f08900-67c4-11eb-9650-3c9dd1c5e72d.png)

What link should be used for the last one?

Can you send a PR to fix these links? The file to update is https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/notification-hubs.md

**Comment by mpodwysocki** [comment]
@ramya-rao-a done: https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/1073

**Comment by ramya-rao-a** [comment]
Thanks @mpodwysocki!
