### ISSUE TITLE
Bad tutorial link

### ISSUE THREAD

**Issue by deyaaeldeen** [MicrosoftDocs/azure-docs-sdk-node#753]
I get page not found error when I click on "Developing a JavaScript app using CosmosDB API" which is a link to https://azure.microsoft.com/en-us/resources/samples/azure-cosmos-db-documentdb-nodejs-getting-started/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc14d27f-a7d3-2a8a-07c2-1d73943cf84b
* Version Independent ID: 217fca5f-eb24-50aa-1530-cc82d767ea91
* Content: [Azure Cosmos DB Modules for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/cosmos-db?view=azure-node-latest)
* Content Source: [docs-ref-services/cosmos-db.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/cosmos-db.md)
* Service: **cosmos-db**
* GitHub Login: @SnehaGunda
* Microsoft Alias: **sngun**

**Comment by ramya-rao-a** [comment]
@zfoster Can you fix this link at https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/latest/cosmos-db.md?

**Comment by ramya-rao-a** [comment]
Closing this issue in favor of https://github.com/Azure/azure-sdk-for-js/issues/13518
