### ISSUE TITLE
samples are 404 jackasses

### ISSUE THREAD

**Issue by tony-gutierrez** [MicrosoftDocs/azure-docs-sdk-node#759]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed4eae4e-e7aa-913c-b37e-4c030e7e21b0
* Version Independent ID: 49051203-4c9a-afe3-e6a6-d34ca1d9426b
* Content: [Azure Active Directory Modules for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/activedirectory?view=azure-node-latest)
* Content Source: [docs-ref-services/activedirectory.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/activedirectory.md)
* Product: **azure**
* Technology: **azure**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by ramya-rao-a** [comment]
@CelesteDG I see that the links were removed in https://github.com/CelesteDG/azure-docs-sdk-node/commit/788d8391bfd3b0e2b092018542f2cab172f5d8f7, but references to the samples still remain. What is the use of listing samples, but not having any links to them? If we do not want to highlight these samples, shouldnt the listing be removed as well?

**Comment by CelesteDG** [comment]
> @CelesteDG I see that the links were removed in [CelesteDG@788d839](https://github.com/CelesteDG/azure-docs-sdk-node/commit/788d8391bfd3b0e2b092018542f2cab172f5d8f7), but references to the samples still remain. What is the use of listing samples, but not having any links to them? If we do not want to highlight these samples, shouldnt the listing be removed as well?

Good call out, @ramya-rao-a - I initially couldn't make any changes to that page without going through other folks but I see now that I'm able to edit it. I'll update to make sure we send a link here: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries

**Comment by ramya-rao-a** [comment]
Thanks @CelesteDG!

The corresponding PR #1058 is merged and the content should go live soon!
