### ISSUE TITLE
parameter name changed to includeTotalCount

### ISSUE THREAD

**Issue by johnpbaldwin** [MicrosoftDocs/azure-docs-sdk-node#856]
This page says to get the search result count, use a parameter called "includeTotalResultCount" which is no longer correct as of 11.0.0 (per the changeling). The correct parameter name is includeTotalCount. In 11.0.3 (perhaps other versions as well), the old parameter name fails to return a count.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71857399-795d-8987-e076-419107564600
* Version Independent ID: bbdda1cc-8bcc-f451-adc3-336cdc222621
* Content: [Azure Cognitive Search client library for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/search-documents-readme?view=azure-node-latest)
* Content Source: [docs-ref-services/search-documents-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/search-documents-readme.md)
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @johnpbaldwin and apologies for the delay in response.

The source of this page is https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/search/search-documents/readme.md which populates the https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/search-documents-readme.md on each release of the package. So, will move this to the https://github.com/Azure/azure-sdk-for-js repo to ensure we fix this in the right place.

**Comment by ramya-rao-a** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-js/issues/13082
