### ISSUE TITLE
Incorrect parameter name IncludeTotalResultCount

### ISSUE THREAD

**Issue by dereklegenzoff** [MicrosoftDocs/azure-docs-sdk-node#918]
Hi there - there parameter named `IncludeTotalResultCount` that is mentioned in this article is incorrect. The correct name is `includeTotalCount`. I believe this needs to be updated elsewhere in the docs as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71857399-795d-8987-e076-419107564600
* Version Independent ID: bbdda1cc-8bcc-f451-adc3-336cdc222621
* Content: [Azure Cognitive Search client library for JavaScript](https://docs.microsoft.com/en-us/javascript/api/overview/azure/search-documents-readme?view=azure-node-latest)
* Content Source: [docs-ref-services/search-documents-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/search-documents-readme.md)
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @dereklegenzoff 

We will track this in https://github.com/Azure/azure-sdk-for-js/issues/13082
