### ISSUE TITLE
Azure tools for Node.js developers - Remove Steps text

### ISSUE THREAD

**Issue by jawache** [MicrosoftDocs/azure-docs-sdk-node#94]
At a glance this reads as the only way to use Azure is by installing the CLI **and** by using Code (step 2 of a 2 step process).

Suggest we remove the "Step 1/2"?

![screenshot 2017-07-17 16 58 11](https://user-images.githubusercontent.com/897523/28277471-fd6ac1c0-6b11-11e7-9629-51a0e1d3e834.png)

**Comment by craigshoemaker** [comment]
this is taken care of via this committ: 242900f197f9f54a20d4b8a82cb3bc2b754b1edb

**Comment by craigshoemaker** [comment]
Closing as a result of the above commit.
