### ISSUE TITLE
Lack of administratorType property in SqlManagementModels.ServerAzureADAdministrator

### ISSUE THREAD

**Issue by xzf0587** [MicrosoftDocs/azure-docs-sdk-node#998]
When I want to set a AAD admin for SQL by @azure/arm-sql, the class of SqlManagementModels.ServerAzureADAdministrator has no property about administratorType  which is required by azure rest api doc [https://docs.microsoft.com/en-us/rest/api/sql/serverazureadadministrators/createorupdate](url). And I indeed failed by warning lack of this property.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @xzf0587 
I have copied this issue to https://github.com/Azure/azure-sdk-for-js/issues/13083 which is the right repo for questions on `@azure/arm-sql` package. Please subscribe to the copied issue
